issue-72 | HOC plop generator file updated
pagesource/atomic-react-components pull request #73
Opened 2019-10-14 10:10 UTC by bhardwajamit0890

2019-10-16 04:31 UTC, vinodloha requested changes
Do this small change please

2019-10-16 04:31 UTC, vinodloha commented on generators/component/index.js
> +      choices: () => ['Stateless Function', 'React.Component', 'hoc'],
Let's keep the option as HOC

2019-10-16 05:00 UTC, vinodloha commented on generators/component/hoc.js.hbs
> +const {{ properCase name}} = Component => {
This template is not enough. Have minimum imports. I.e React, types definitions etc. 
Rename Component as WrappedComponent.

Template should looks like below: 
```
import React from 'react';

import getDisplayName from '../../core/utils/getDisplayName';

const {{ properCase name}} = WrappedComponent => {
  // ...and returns another component...
  class extends React.Component {
    constructor(props) {
      super(props);
      this.state = {};
    }

    render() {
    
      return <WrappedComponent {...this.props} />;
    }
  };
  {{ properCase name}}.displayName = `{{ properCase name}}(${getDisplayName(WrappedComponent)})`;
  return {{ properCase name}};
}
``` 

Also create a file at core/utils with following content. 
function getDisplayName(WrappedComponent) {
  return WrappedComponent.displayName || WrappedComponent.name || 'Component';
}

2019-10-16 05:01 UTC, vinodloha requested changes

2019-10-16 05:01 UTC, vinodloha commented on generators/utils/componentExists.js
> +const hoc = fs.readdirSync(path.join(__dirname, '../../lib/components/hoc'));
I believe we are also creating test/* dir and files too.

2019-10-18 16:39 UTC, bhardwajamit0890 commented
Done

2019-11-07 18:04 UTC, merged