Tooltip component created
pagesource/atomic-react-components pull request #9
Opened 2019-03-15 10:44 UTC by ssi114

2019-03-18 04:02 UTC, vinodloha commented
@ssi114 Can you check why CI build is failing and fix it?

2019-03-18 04:04 UTC, vinodloha commented on lib/components/atoms/Tooltip/Tooltip.js
> +      <span className={className} onMouseLeave={this.hideTooltip}>
@ssi114 Do you think Span is the right tag for building tooltip?

2019-03-18 04:47 UTC, vinodloha requested changes
Doesn't take care of web accessibility:
https://www.w3.org/TR/wai-aria-practices-1.1/#tooltip  
https://www.sarasoueidan.com/blog/accessible-tooltips/

2019-03-18 04:47 UTC, vinodloha commented on lib/components/atoms/Tooltip/Tooltip.js
> +            <div className="tooltip-message">{message}</div>
@ssi114 i would expect tool tip to get triggered from existing components like Button

2019-04-05 02:31 UTC, vinodloha requested changes
@ssi114 Please fix these review comments.

2019-04-08 19:28 UTC, vinodloha commented on lib/components/atoms/Tooltip/Tooltip.js
> +    message: '',
This Props will not be string.

2019-04-08 19:29 UTC, vinodloha commented on lib/components/atoms/Tooltip/Tooltip.js
> +  render() {
You should use react portal so that tooltip doesn't get cropped because of overflow hidden on parent.

2019-04-08 19:29 UTC, vinodloha commented on lib/components/atoms/Tooltip/tests/Tooltip.test.js
> +  test('should render correctly', () => {
This test will not be enough

2019-04-08 19:30 UTC, vinodloha requested changes
There are still lot of things to fix @ssi114

2019-04-11 02:52 UTC, vinodloha commented on lib/components/atoms/Tooltip/Tooltip.js
> +class Tooltip extends Component<Props, State> {
@ssi114 this component can be PureComponent and not a Component

2019-04-11 02:53 UTC, vinodloha commented on lib/components/atoms/Tooltip/Tooltip.js
> +    document.addEventListener('keyup', (e: KeyboardEvent) => {
keyup event should change to keydown

2019-04-11 02:55 UTC, vinodloha commented on lib/components/atoms/Tooltip/Tooltip.js
> +          {children}
Children should be body of tooltip and not the trigger

2019-10-15 04:51 UTC, sohonisaurabh commented
@vinodloha I am picking up this task

2019-11-14 07:33 UTC, closed without merging